version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: 975317438117.dkr.ecr.us-east-1.amazonaws.com/nocobase:7a6b0b2b057d766c78921ce0314a7547145404db
    networks:
      - nocobase
    environment:
      - LOCAL_STORAGE_BASE_URL=http://localhost:13000/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:13000"